#!/usr/bin/env bash
# scripts/gate-fixtures.sh — gate GATE-DISCRIMINATES.
#
# RULE: every gate exits 1 on its committed violating fixture and 0 on its
# committed clean fixture.
#
# WHY THIS GATE EXISTS: it is the executable form of the core principle —
# "a gate that never fires is indistinguishable from a broken gate, and that is
# how most of them are born." Everything else in this repo trusts the gates. If
# a gate silently stops discriminating, every check that depends on it turns
# green for the wrong reason, and green is exactly the state nobody
# investigates.
#
# This is not hypothetical here. gate-reachable.sh's first fixtures passed for
# the wrong reason (its own header comments named the scripts it was looking
# for, so mutations that severed every real call still came back green), and
# during the /ctx-* rename a new --count flag silently broke
# gate-eval-prompt-purity.sh's positional argument — it began exiting 2 on BOTH
# fixtures. Only a both-directions check catches that: exit 2 on the violating
# fixture is "non-zero", which a naive test reads as success.
#
# DETECTION: discover every gate, resolve its fixture pair, run it twice, and
# require exactly exit 1 then exit 0. Not "non-zero then zero" — exactly 1,
# because 2 means the gate itself broke and must never read as a catch.
#
# Fixtures are resolved two ways:
#   1. gates/fixtures/<RULE-ID>/{violating,clean}.*  — the convention for gates
#      generated by /ctx-gate from a rule page
#   2. scripts/gate-fixtures.tsv — an explicit table for the hand-written gates
#      in scripts/, whose fixtures predate the convention and take gate-specific
#      flags (--diff, --repo, --index) that cannot be guessed
#
# A gate with NO fixture pair in either place is a violation, not a skip. That
# is the whole point: an unfixtured gate is an unproven one.
#
# FAILURE MODES — the honest ones:
#   - It proves a gate discriminates on the ONE violation its fixture plants. A
#     gate that catches its fixture and nothing else passes here. The five-way
#     mutation proof (§5) is what covers that, and it is a human step.
#   - A fixture that drifts to plant a *different* violation than the rule
#     describes still passes, as long as the gate fires on it.
#   - Exit codes only. A gate that fires with a useless message passes.
#
# SCOPE: scripts/gate-*.sh and gates/*.sh. Excludes gate-ratchet.sh and this
# script (both have fixtures, but running them here would recurse), and excludes
# the wiki-lint-* family, which reports on user content rather than asserting a
# rule about the repo.
#
# EXIT: 0 = every gate discriminates · 1 = a gate failed a direction, or has no
#       fixtures · 2 = the gate itself failed (no gates found, unreadable table).
#
# MODES:
#   (default)   check this repository
#   --count     print "<violations>TAB<suppressions>" and exit 0
#
# RUNTIME: bash 3.2+. No LLM, no network, no key.
# WIRED AT: scripts/smoke-all.sh (R31) → CI.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/gate-lib.sh
. "$SCRIPT_DIR/lib/gate-lib.sh" || { printf 'gate-fixtures: cannot source lib/gate-lib.sh\n' >&2; exit 2; }
gate_init "gate-fixtures" "GATE-DISCRIMINATES"

ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo)  ROOT="${2:-}"; [ -n "$ROOT" ] || gate_die "--repo needs a directory"; shift 2 ;;
    --count) GATE_COUNT_MODE=1; shift ;;
    *) gate_die "unknown argument: $1" ;;
  esac
done
[ -d "$ROOT" ] || gate_die "not a directory: $ROOT"
cd "$ROOT" || gate_die "cannot cd to $ROOT"

TABLE="scripts/gate-fixtures.tsv"

# Gates that cannot be checked from inside this script.
self_exempt() {
  case "$1" in
    scripts/gate-fixtures.sh) return 0 ;;   # would recurse
    scripts/gate-ratchet.sh)  return 0 ;;   # invokes every gate; recurses
    *) return 1 ;;
  esac
}

# run_pair <label> <expect1-cmd> <expect0-cmd>
# Requires EXACTLY 1 then EXACTLY 0.
run_pair() {
  _label="$1"; _dirty="$2"; _clean="$3"
  # shellcheck disable=SC2086
  eval "$_dirty" >/dev/null 2>&1
  _rc_dirty=$?
  # shellcheck disable=SC2086
  eval "$_clean" >/dev/null 2>&1
  _rc_clean=$?

  if [ "$_rc_dirty" -ne 1 ]; then
    if [ "$_rc_dirty" -eq 0 ]; then
      gate_violation "$_label:1" \
"passed its VIOLATING fixture (exit 0). The gate no longer detects the thing it
       exists to detect. Run: $_dirty"
    else
      gate_violation "$_label:1" \
"exited $_rc_dirty on its violating fixture, not 1. Exit 2 means the GATE broke,
       not that it caught something — a test accepting any non-zero would read
       this as success. Run: $_dirty"
    fi
  fi

  if [ "$_rc_clean" -ne 0 ]; then
    gate_violation "$_label:1" \
"failed its CLEAN fixture (exit $_rc_clean). The gate fires on compliant input,
       which is how a gate gets suppressed rather than obeyed. Run: $_clean"
  fi
}

pairs=0

# ── 1. table-driven fixtures (the hand-written gates in scripts/) ──
# Format: <gate-path><TAB><violating-invocation><TAB><clean-invocation>
if [ -r "$TABLE" ]; then
  lineno=0
  while IFS= read -r row || [ -n "$row" ]; do
    lineno=$((lineno + 1))
    case "$row" in ''|'#'*) continue ;; esac
    gpath="$(printf '%s' "$row" | cut -f1)"
    dirty="$(printf '%s' "$row" | cut -f2)"
    clean="$(printf '%s' "$row" | cut -f3)"
    [ -n "$gpath" ] && [ -n "$dirty" ] && [ -n "$clean" ] \
      || gate_die "$TABLE:$lineno: needs three tab-separated fields"
    [ -f "$gpath" ] || gate_die "$TABLE:$lineno: names $gpath, which does not exist"
    pairs=$((pairs + 1))
    run_pair "$gpath" "$dirty" "$clean"
  done < "$TABLE"
fi

# ── 2. convention-driven fixtures (gates generated by /ctx-gate) ──
for g in gates/*.sh; do
  [ -f "$g" ] || continue
  rule_id="$(basename "$g" .sh)"
  fdir="gates/fixtures/$rule_id"
  v="$(find "$fdir" -maxdepth 1 -name 'violating.*' -type f 2>/dev/null | head -1)"
  c="$(find "$fdir" -maxdepth 1 -name 'clean.*'     -type f 2>/dev/null | head -1)"
  if [ -z "$v" ] || [ -z "$c" ]; then
    gate_violation "$g:1" \
"no fixture pair at $fdir/. An unfixtured gate is an unproven one — nothing
       shows it has ever fired. Add violating.<ext> and clean.<ext>, then prove
       both directions."
    continue
  fi
  pairs=$((pairs + 1))
  run_pair "$g" "bash '$g' --repo '$fdir/violating-tree' 2>/dev/null || bash '$g' '$v'" \
                "bash '$g' --repo '$fdir/clean-tree' 2>/dev/null || bash '$g' '$c'"
done

# ── 3. the converse: a gate with no fixtures anywhere ──
for g in scripts/gate-*.sh; do
  [ -f "$g" ] || continue
  self_exempt "$g" && continue
  if [ -r "$TABLE" ] && grep -q "^$(printf '%s' "$g" | sed 's/[].[^$\\*/]/\\&/g')$(printf '\t')" "$TABLE"; then
    continue
  fi
  gate_violation "$g:1" \
"this gate has no row in $TABLE and no gates/fixtures/ directory, so nothing
       proves it discriminates. Per deterministic-gates §4, a gate ships with
       one fixture that VIOLATES (must exit 1) and one CLEAN file (must exit 0).
       Add both, then register the invocations in $TABLE."
done

# No fixture pairs has two causes. A compiler freshly made by the installer
# ships gates but no gates/ of its own and no fixture table — there is genuinely
# nothing to check yet. A repo that HAS gates and no fixtures is the failure
# this gate exists to name, and the loop above has already recorded one
# violation per unfixtured gate, so falling through to the verdict is correct.
if [ "$pairs" -eq 0 ] && [ "$GATE_VIOLATIONS" -eq 0 ]; then
  gate_verdict "clean — no gates with fixtures yet; nothing claims to be proven."
fi

gate_verdict "clean — $pairs gate(s) fail their violating fixture and pass their clean one."
