#!/usr/bin/env bash
# scripts/registry.sh — owner of the multi-wiki registry (registry.jsonl).
#
# The registry is a LOCAL catalog of every wiki generated by the factory. It
# lives at the WORKSPACE root (not in this dev repo) as one flat JSON object
# per line:
#
#   {"name":"my-deals","domain":"M&A due-diligence tracking","path":"my-deals",
#    "in_workspace":true,"created":"2026-05-29","schema":"v2","seeded":false}
#
# Key order is fixed (name, domain, path, in_workspace, created, schema, seeded)
# so the readers below can anchor on the next literal key without a JSON parser.
# `path` is RELATIVE to the workspace when in_workspace:true, ABSOLUTE otherwise.
#
# This script is the ONE allowed writer/reader of registry.jsonl. No `jq`, no
# `python3` — printf + sed + awk only, Bash 3.2 safe (matches create-llm-wiki.sh).
#
# Usage:
#   scripts/registry.sh [--workspace <dir>] <subcommand> [args]
#
# Subcommands:
#   add --name N --domain D --path P --in-workspace true|false [--created DATE] [--schema S] [--seeded true|false]
#                         append a new entry (refuses a duplicate name)
#   mark-seeded <name>    flip an entry's seeded flag false -> true
#   has <name>            exit 0 if an entry exists, 1 otherwise (no output)
#   list                  render a table; flag drift (MISSING dirs, UNREGISTERED dirs)
#   prune [--apply [--yes]]  report dangling entries (dir gone); --apply removes
#                            them after a [y/N] confirm; --yes skips the confirm
#                            (for automation — registry.jsonl edit is irreversible)
#
# Default workspace: ${LLM_WIKI_WORKSPACE:-$HOME/llm-wikis}

set -euo pipefail

WORKSPACE="${LLM_WIKI_WORKSPACE:-$HOME/llm-wikis}"

# --- leading global flag: --workspace -------------------------------------
while [ "$#" -gt 0 ]; do
  case "$1" in
    --workspace) WORKSPACE="$2"; shift 2 ;;
    --workspace=*) WORKSPACE="${1#*=}"; shift ;;
    *) break ;;
  esac
done

REG="$WORKSPACE/registry.jsonl"

[ "$#" -ge 1 ] || { echo "error: no subcommand (add|has|mark-seeded|list|prune)" >&2; exit 2; }
SUB="$1"; shift

# --- helpers ---------------------------------------------------------------

# JSON-escape a string value: backslash, doublequote; collapse CR/LF/TAB to space.
json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/ }"
  s="${s//$'\r'/ }"
  s="${s//$'\t'/ }"
  printf '%s' "$s"
}

# Extract a quoted-string field from a single registry line.
# Args: <line> <key> <next-key-or-empty>. Anchors on the next literal key when
# given (so free-text values like `domain` are captured whole), else on `","`.
json_str() {
  local line="$1" key="$2" next="$3"
  # NOTE: feed sed a newline-terminated line — BSD/macOS sed preserves a missing
  # trailing newline, which would concatenate successive field reads.
  if [ -n "$next" ]; then
    printf '%s\n' "$line" | sed -n 's/.*"'"$key"'":"\(.*\)","'"$next"'":.*/\1/p'
  else
    printf '%s\n' "$line" | sed -n 's/.*"'"$key"'":"\([^"]*\)".*/\1/p'
  fi
}

# Extract a boolean field (true|false) from a line. Captures the lowercase-letter
# run after `"key":` — portable BRE, no `\|` alternation (BSD/macOS sed lacks it).
json_bool() {
  printf '%s\n' "$1" | sed -n 's/.*"'"$2"'":\([a-z][a-z]*\).*/\1/p'
}

# Whole-line membership test, pure shell (no grep -q pipe — that risks SIGPIPE
# killing a slow upstream producer under `set -o pipefail`). Args: <needle> <newline-list>.
in_list() {
  case "
$2
" in
    *"
$1
"*) return 0 ;;
  esac
  return 1
}

# Names already in the registry (one per line). Empty if no registry.
registry_names() {
  [ -f "$REG" ] || return 0
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    json_str "$line" name domain
  done < "$REG"
}

# Resolve an entry's on-disk path. Args: <path> <in_workspace>.
resolve_path() {
  if [ "$2" = "true" ]; then printf '%s' "$WORKSPACE/$1"; else printf '%s' "$1"; fi
}

# --- subcommands -----------------------------------------------------------

case "$SUB" in
  add)
    name="" domain="" path="" in_ws="" created="" schema="v2" seeded="false"
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --name) name="$2"; shift 2 ;;
        --domain) domain="$2"; shift 2 ;;
        --path) path="$2"; shift 2 ;;
        --in-workspace) in_ws="$2"; shift 2 ;;
        --created) created="$2"; shift 2 ;;
        --schema) schema="$2"; shift 2 ;;
        --seeded) seeded="$2"; shift 2 ;;
        *) echo "error: add: unknown flag $1" >&2; exit 2 ;;
      esac
    done
    [ -n "$name" ] && [ -n "$path" ] && [ -n "$in_ws" ] || {
      echo "error: add requires --name, --path, --in-workspace" >&2; exit 2; }
    [ -n "$created" ] || created="$(date +%F)"

    mkdir -p "$WORKSPACE"

    # Refuse a duplicate name so the catalog stays clean.
    if [ -f "$REG" ] && in_list "$name" "$(registry_names)"; then
      echo "error: registry already has an entry named '$name' in $REG" >&2
      exit 1
    fi

    printf '{"name":"%s","domain":"%s","path":"%s","in_workspace":%s,"created":"%s","schema":"%s","seeded":%s}\n' \
      "$(json_escape "$name")" "$(json_escape "$domain")" "$(json_escape "$path")" \
      "$in_ws" "$(json_escape "$created")" "$(json_escape "$schema")" "$seeded" >> "$REG"
    echo "✓ registered '$name' in $REG"
    ;;

  has)
    name="${1:?usage: registry.sh has <name>}"
    [ -f "$REG" ] || exit 1
    if in_list "$name" "$(registry_names)"; then exit 0; else exit 1; fi
    ;;

  mark-seeded)
    name="${1:?usage: registry.sh mark-seeded <name>}"
    [ -f "$REG" ] || { echo "error: no registry at $REG" >&2; exit 1; }
    tmp="$REG.tmp.$$"
    found=0
    while IFS= read -r line; do
      [ -n "$line" ] || continue
      if [ "$(json_str "$line" name domain)" = "$name" ]; then
        printf '%s\n' "$line" | sed 's/"seeded":false}$/"seeded":true}/'
        found=1
      else
        printf '%s\n' "$line"
      fi
    done < "$REG" > "$tmp"
    mv "$tmp" "$REG"
    if [ "$found" -eq 1 ]; then
      echo "✓ marked '$name' seeded in $REG"
    else
      echo "error: no entry named '$name' in $REG" >&2; exit 1
    fi
    ;;

  list)
    if [ ! -f "$REG" ] || [ ! -s "$REG" ]; then
      echo "No wikis registered. Workspace: $WORKSPACE"
      echo "(create one with: scripts/new-wiki.sh <name> --domain \"...\")"
      exit 0
    fi
    echo "Workspace: $WORKSPACE"
    echo
    printf '%-20s %-8s %-7s %s\n' "NAME" "SEEDED" "STATUS" "DOMAIN"
    printf '%-20s %-8s %-7s %s\n' "----" "------" "------" "------"
    while IFS= read -r line; do
      [ -n "$line" ] || continue
      name="$(json_str "$line" name domain)"
      domain="$(json_str "$line" domain path)"
      path="$(json_str "$line" path in_workspace)"
      in_ws="$(json_bool "$line" in_workspace)"
      seeded="$(json_bool "$line" seeded)"
      rp="$(resolve_path "$path" "$in_ws")"
      if [ -d "$rp" ]; then status="ok"; else status="MISSING"; fi
      [ "$seeded" = "true" ] && sflag="yes" || sflag="pending"
      printf '%-20s %-8s %-7s %s\n' "$name" "$sflag" "$status" "$domain"
    done < "$REG"

    # Unregistered dirs sitting in the workspace (drift the other direction).
    if [ -d "$WORKSPACE" ]; then
      names="$(registry_names)"
      shopt -s nullglob
      for d in "$WORKSPACE"/*/; do
        b="$(basename "$d")"
        if ! in_list "$b" "$names"; then
          echo "  UNREGISTERED: $b (dir present in workspace, no registry entry)"
        fi
      done
      shopt -u nullglob
    fi
    ;;

  prune)
    apply=0
    assume_yes=0
    for arg in "$@"; do
      case "$arg" in
        --apply)            apply=1 ;;
        --yes|-y|--force)   assume_yes=1 ;;
      esac
    done
    [ -f "$REG" ] || { echo "No registry at $REG — nothing to prune."; exit 0; }
    tmp="$REG.tmp.$$"
    removed=0
    : > "$tmp"
    while IFS= read -r line; do
      [ -n "$line" ] || continue
      path="$(json_str "$line" path in_workspace)"
      in_ws="$(json_bool "$line" in_workspace)"
      name="$(json_str "$line" name domain)"
      rp="$(resolve_path "$path" "$in_ws")"
      if [ -d "$rp" ]; then
        printf '%s\n' "$line" >> "$tmp"
      else
        echo "dangling: $name -> $rp (dir gone)"
        removed=$((removed + 1))
      fi
    done < "$REG"
    if [ "$removed" -eq 0 ]; then
      rm -f "$tmp"
      echo "✓ no dangling entries."
    elif [ "$apply" -eq 1 ]; then
      if [ "$assume_yes" -ne 1 ]; then
        echo
        printf "Remove the %d dangling entrie(s) listed above from the catalog? [y/N] " "$removed"
        read -r reply
        case "$reply" in
          y|Y|yes|YES) ;;
          *) rm -f "$tmp"; echo "Aborted — registry unchanged."; exit 1 ;;
        esac
      fi
      mv "$tmp" "$REG"
      echo "✓ pruned $removed dangling entrie(s) from $REG"
    else
      rm -f "$tmp"
      echo "($removed dangling; re-run with --apply to remove)"
    fi
    ;;

  *)
    echo "error: unknown subcommand '$SUB' (add|has|mark-seeded|list|prune)" >&2
    exit 2
    ;;
esac
