#!/usr/bin/env python3
"""Mechanical synthesis generators for the llm-wiki.

Regenerates the cross-cutting *synthesis* pages from markers the LLM already
wrote during ingest — it performs no semantic work of its own, only
aggregation. This is what makes "regenerate on every wiki mutation" affordable
(zero LLM cost) and safe (deterministic bytes ⇒ no git churn when nothing
changed).

Generated pages (all `type: navigation`, all carrying the AUTO-GENERATED
marker so /wiki-lint and humans leave them alone):

  open-questions-dashboard.md  ← every `## Open questions on this page` section
  tensions.md                  ← every `> CONTRADICTION FLAGGED …` blockquote
  decision-timeline.md         ← reverse-chronological log.md activity timeline

The graph artifact (knowledge-graph.json) is emitted separately by
scripts/visualize/graph-html.py --json (reuses the same parser the D3 view
uses), orchestrated by all.sh — not here.

Stdlib only. Deterministic: sorted iteration, dates derived from data (never
the wall clock).

Usage:
  build.py --wiki <wiki-dir> --log <log.md> [--only open-questions|tensions|timeline]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Pages this script generates — excluded from every scan so re-runs never
# aggregate their own output recursively.
GENERATED = ("open-questions-dashboard.md", "tensions.md", "decision-timeline.md")

AUTO_MARKER = (
    "<!-- AUTO-GENERATED by scripts/synthesize; do not hand-edit — "
    "regenerated on every ingest / query-promote / lint-apply -->"
)

OPEN_Q_HEADING_RE = re.compile(r"^##\s+Open questions on this page\s*$")
SECTION_RE = re.compile(r"^##\s+")
BULLET_RE = re.compile(r"^-\s+(.*\S)\s*$")
UPDATED_RE = re.compile(r"^updated:\s*(\d{4}-\d{2}-\d{2})\s*$")
CONTRADICTION_RE = re.compile(r"^>\s*CONTRADICTION FLAGGED\s+(\d{4}-\d{2}-\d{2}):\s*(.*\S)\s*$")
# Time is optional: log.md mixes timestamped command entries
# (`## 2026-06-03 09:00 — /wiki-ingest`) with date-only summary headers
# (`## 2026-06-09 — schema v2 → v3`). Both must appear on the timeline.
LOG_ENTRY_RE = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})(?:\s+(\d{2}:\d{2}))?\s+[—-]\s+(.*\S)\s*$")
DATE_FALLBACK = "1970-01-01"


def source_pages(wiki_dir: Path) -> list[Path]:
    """Sorted *.md under wiki_dir, excluding the pages we generate."""
    return sorted(p for p in wiki_dir.rglob("*.md") if p.name not in GENERATED)


def is_placeholder_question(text: str) -> bool:
    """Skip the empty template stub `- ... (consumed by /wiki-lint)`."""
    return text.startswith("...")


def collect_open_questions(pages: list[Path]) -> list[tuple[str, list[str]]]:
    """Return [(page_slug, [question, ...]), ...] for pages that have any."""
    out: list[tuple[str, list[str]]] = []
    for page in pages:
        in_section = False
        questions: list[str] = []
        for line in page.read_text(encoding="utf-8", errors="replace").splitlines():
            if OPEN_Q_HEADING_RE.match(line):
                in_section = True
                continue
            if in_section and SECTION_RE.match(line):
                break
            if in_section:
                m = BULLET_RE.match(line)
                if m and not is_placeholder_question(m.group(1)):
                    questions.append(m.group(1))
        if questions:
            out.append((page.stem, questions))
    return out


def collect_contradictions(pages: list[Path]) -> list[tuple[str, str, str]]:
    """Return sorted [(date, page_slug, description), ...]."""
    out: list[tuple[str, str, str]] = []
    for page in pages:
        for line in page.read_text(encoding="utf-8", errors="replace").splitlines():
            m = CONTRADICTION_RE.match(line)
            if m:
                out.append((m.group(1), page.stem, m.group(2)))
    # newest first, then page slug for stable tie-break
    return sorted(out, key=lambda t: (t[0], t[1]), reverse=True)


def collect_log_entries(log_path: Path) -> list[tuple[str, str, str]]:
    """Return [(date, time, command-line), ...] newest-first from log.md headers."""
    if not log_path.is_file():
        return []
    out: list[tuple[str, str, str]] = []
    for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = LOG_ENTRY_RE.match(line)
        if m:
            out.append((m.group(1), m.group(2) or "", m.group(3)))
    # log.md is already newest-at-top; sort defensively (date+time desc). Date-only
    # entries (time == "") sort after timestamped ones on the same date.
    return sorted(out, key=lambda t: (t[0], t[1]), reverse=True)


def freshness(pages: list[Path], log_entries: list[tuple[str, str, str]]) -> str:
    """Max ISO date across source-page `updated:` fields and log dates.

    Deterministic stand-in for the page's own `updated:` — changes only when
    the underlying content does, never on a mere re-run.
    """
    dates: list[str] = [d for (d, _t, _c) in log_entries]
    for page in pages:
        for line in page.read_text(encoding="utf-8", errors="replace").splitlines():
            m = UPDATED_RE.match(line)
            if m:
                dates.append(m.group(1))
                break  # frontmatter updated: is the first match
    return max(dates) if dates else DATE_FALLBACK


def frontmatter(title: str, updated: str, tags: list[str]) -> str:
    # Frontmatter must be the very first thing on the page (lint check #7), so the
    # AUTO-GENERATED marker goes immediately after it, not before.
    return (
        "---\n"
        f"title: {title}\n"
        "type: navigation\n"
        "source: analysis\n"
        f"updated: {updated}\n"
        f"tags: [{', '.join(tags)}]\n"
        "---\n"
        "\n"
        f"{AUTO_MARKER}"
    )


def render_open_questions(items: list[tuple[str, list[str]]], updated: str) -> str:
    body = [
        frontmatter("Open Questions Dashboard", updated, ["synthesis", "open-questions", "navigation"]),
        "",
        "# Open Questions Dashboard",
        "",
        "Auto-aggregated from every `## Open questions on this page` section across "
        "the wiki. For the manual, system-level gaps page see [[open-questions]].",
        "",
    ]
    if not items:
        body.append("_No open questions recorded on any page._")
    else:
        for slug, questions in items:
            body.append(f"## [[{slug}]]")
            body.extend(f"- {q}" for q in questions)
            body.append("")
    return "\n".join(body).rstrip() + "\n"


def render_tensions(rows: list[tuple[str, str, str]], updated: str) -> str:
    body = [
        frontmatter("Tensions", updated, ["synthesis", "contradictions", "navigation"]),
        "",
        "# Tensions",
        "",
        "Auto-aggregated from every `> CONTRADICTION FLAGGED` flag in the wiki. "
        "Each contradiction is flagged on both conflicting pages; resolve by editing "
        "the raw source and re-running `/wiki-ingest`, or via `/wiki-lint --apply`.",
        "",
    ]
    if not rows:
        body.append("_No contradictions currently flagged._")
    else:
        for date, slug, desc in rows:
            body.append(f"- **{date}** — in [[{slug}]]: {desc}")
    return "\n".join(body).rstrip() + "\n"


def render_timeline(entries: list[tuple[str, str, str]], updated: str) -> str:
    body = [
        frontmatter("Decision Timeline", updated, ["synthesis", "timeline", "navigation"]),
        "",
        "# Decision Timeline",
        "",
        "Reverse-chronological activity timeline parsed from every `log.md` entry "
        "(ingest / query / lint and other logged events). An activity trail, not a "
        "record of domain decisions.",
        "",
    ]
    if not entries:
        body.append("_No activity logged yet._")
    else:
        for date, time, command in entries:
            stamp = f"**{date}** {time}".rstrip()
            body.append(f"- {stamp} — {command}")
    return "\n".join(body).rstrip() + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    """Write only when bytes differ. Returns True if the file changed."""
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate llm-wiki synthesis pages.")
    parser.add_argument("--wiki", type=Path, required=True, help="wiki/ directory")
    parser.add_argument("--log", type=Path, required=True, help="log.md path")
    parser.add_argument("--only", choices=["open-questions", "tensions", "timeline"],
                        default=None, help="regenerate just one page (default: all three)")
    args = parser.parse_args(argv)

    if not args.wiki.is_dir():
        sys.stderr.write(f"error: not a directory: {args.wiki}\n")
        return 2

    pages = source_pages(args.wiki)
    log_entries = collect_log_entries(args.log)
    updated = freshness(pages, log_entries)

    targets = {
        "open-questions": (
            args.wiki / "open-questions-dashboard.md",
            lambda: render_open_questions(collect_open_questions(pages), updated),
        ),
        "tensions": (
            args.wiki / "tensions.md",
            lambda: render_tensions(collect_contradictions(pages), updated),
        ),
        "timeline": (
            args.wiki / "decision-timeline.md",
            lambda: render_timeline(log_entries, updated),
        ),
    }
    selected = [args.only] if args.only else list(targets)

    changed = []
    for name in selected:
        path, render = targets[name]
        if write_if_changed(path, render()):
            changed.append(path.name)

    if changed:
        sys.stderr.write(f"synthesis: regenerated {', '.join(sorted(changed))}\n")
    else:
        sys.stderr.write("synthesis: no changes\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
